
pipeline {
    agent any
    stages {
        stage('hello AWS') {
            steps {
                withAWS(credentials: 'baranikannan', region: 'ap-southeast-1') {
                    sh '''
                    aws s3 ls
                    cd app
                    terraform init
                    terraform workspace list
                    echo ${app_version}
                    '''
                }
            }
        }
    }
}