pipeline {
  agent any
  options {
    skipDefaultCheckout(true)
  }
  stages{

    stage('terraform') {
      steps {
        sh 'terraformw plan -var-file=test.tfvars -var app_version=v1 -no-color'
      }
    }
  }
    }
  }
}